### ISSUE TITLE
Improve availability of prediction system

### ISSUE THREAD

**Issue by dbaing17** [orcasound/aifororcas-livesystem#19]
The email notifications are working intermittently.  After the first round of failures, it restarted, but has failed again.  It failed on 9/15, resumed working on 9/16, and failed again on 9/17.  It seemed to work flawlessly for almost a year until these failures.

**Comment by micya** [comment]
There has been downtime of multiple hours where humans have heard orcas but no notifications were triggered. There are three potential failure points:

1. Prediction system (running on Azure Container Instances)
2. Notification system (running on Azure Functions)
3. SendGrid

We want to put in the following:

1. Better monitoring to track failure points
2. High availability for prediction system (ACI)

**Comment by micya** [comment]
This issue will track high availability for prediction system (ACI).

**Comment by micya** [comment]
Inference system has been moved to AKS late last year and no major outages has been reported since then. Closing this issue.
