### ISSUE TITLE
Typo in v2 portal Orca Sounds dropdown menu

### ISSUE THREAD

**Issue by scottveirs** [orcasound/aifororcas-livesystem#199]
On the `Orca Sounds` page at [https://aifororcas2.azurewebsites.net/orca_sounds](https://aifororcas2.azurewebsites.net/orca_sounds) there is a minor typo (`Verfied` instead of `Verified`) in the dropdown menu for Unreviewed/Verified/etc:

<img width="805" alt="Screenshot 2024-09-19 at 11 10 37 AM" src="https://github.com/user-attachments/assets/6b2bbea8-4380-4c4f-bd05-e300465f4308">

**Comment by dthaler** [comment]
Fixed by #200
