### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by scottveirs** [orcasound/aifororcas-livesystem#2]
MIT?

**Comment by micya** [comment]
Easy to do. What is the name/organization that should be put on the license?

**Comment by prakruti** [comment]
Organization is Orcasound, see 
https://github.com/orcasound/orca-action-workflow/blob/main/LICENSE

**Comment by scottveirs** [comment]
A Github trick I learned this summer: "Add file->Create new file" from top of repo, then type "license" as new filename and an "Choose a license template" button appears in upper right of editor.

**Comment by prakruti** [comment]
@scottveirs this has been merged, see https://github.com/orcasound/aifororcas-livesystem/pull/27. Closing.
