### ISSUE TITLE
Update data flow schematic for README

### ISSUE THREAD

**Issue by scottveirs** [orcasound/aifororcas-livesystem#91]
As of Sept 2022, the data schematic in the [aifororcas-livesystem README]() indicates the inference model is deployed via _Azure Container Instance_ service. It currently looks like this:

<img width="1032" alt="SystemOverview" src="https://user-images.githubusercontent.com/14044595/188322866-0636e41a-4418-40d2-b78a-57ced5b89b1a.png">

To be more accurate, the [current image](https://github.com/orcasound/aifororcas-livesystem/blob/main/Docs/Images/SystemOverview.png) should be modified to instead indicate that the inference system is deployed via _Azure Kubernetes Service_ ([AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/)).

I'm not sure where this graphic lives (in Microsoft hackathon Teams workspace?) or in what software it was created. Ideally it would be stored within the REPO in a format that could be edited easily in the future, rather than only as an image file.

After updating the file, the README should be proof-read to ensure deployment descriptions are consistent with the new version of the schematic.

**Comment by micya** [comment]
Chatted with @prakruti - image was in "AI for Orcas Hack 2020 Robb.pptx". Will update shortly.
