### ISSUE TITLE
Upon 2nd load, Detail view does not overlay predictions

### ISSUE THREAD

**Issue by scottveirs** [orcasound/aifororcas-livesystem#93]
On Macbook+Chrome, I just experienced a possible minor bug: First I did a normal loading of the Detail view within the moderator portal, then closed the modal, and then happened to re-load the Detail view for the same candidate. Upon the 2nd loading of the modal, the spectrogram appeared, but the prediction delineations (white lines) did not get overlain.

This is a low-priority bug report... Here is a screen grab of the offending candidate/modal:

<img width="1784" alt="Screen Shot 2022-09-08 at 9 04 45 AM" src="https://user-images.githubusercontent.com/14044595/189173864-33f74324-9c0b-48ec-8db6-588485e9b590.png">

**Comment by micowan** [comment]
Scott,

Not sure how I can diagnose/fix this as I have no Macbook/IOS devices to work with. But I guess I'll figure something out.

From: Scott Veirs ***@***.***>
Sent: Thursday, September 8, 2022 12:43 PM
To: orcasound/aifororcas-livesystem ***@***.***>
Cc: Mike Cowan ***@***.***>; Assign ***@***.***>
Subject: [orcasound/aifororcas-livesystem] Upon 2nd load, Detail view does not overlay predictions (Issue #93)


On Macbook+Chrome, I just experienced a possible minor bug: First I did a normal loading of the Detail view within the moderator portal, then closed the modal, and then happened to re-load the Detail view for the same candidate. Upon the 2nd loading of the modal, the spectrogram appeared, but the prediction delineations (white lines) did not get overlain.

This is a low-priority bug report... Here is a screen grab of the offending candidate/modal:

[Screen Shot 2022-09-08 at 9 04 45 AM]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F14044595%2F189173864-33f74324-9c0b-48ec-8db6-588485e9b590.png&data=05%7C01%7Cmicowan%40microsoft.com%7C6bcf0c6392de4e076d6a08da91b92bd1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637982521746294072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jZyO1%2FGoXhxDzwFYx%2BWTGH253Fsh6%2BObQ3PRyNeZYbw%3D&reserved=0>

-

**Comment by scottveirs** [comment]
Hey Mike,

It's minor enough that I think we could deprioritize for the 2022
hackathon, then wait til we get a volunteer dev who works on iOS and can
easily test/de-bug. Alternatively, i'd be happy to try to debug with you
during the hackathon, or team up you/other devs with e.g. a UX/design
person who has a Mac and would enjoy the process of learning how to debug
part of the front end.
