### ISSUE TITLE
Bulk annotation or "repeat" button

### ISSUE THREAD

**Issue by scottveirs** [orcasound/aifororcas-livesystem#99]
**As a moderator working alone (thereby avoiding back-end conflicts with other authenticated moderators?!)
facing a long backlog of repetitive false positives (currently there are 1750 unmoderated candidates)
I want to be able to annotate many candidates simultaneously/efficiently with the same `tag` and `comment` field values**

This could be *much* faster than my current workflow, after listening to the candidate, usually using the "Detailed" view: 

1. Hit "no" radio button
2. Type in tags
3. Type in comments
4. Hit submit

There are at least 3 ways that I can imagine accelerating the moderation process:

A:
1. Moderate first candidate
2. Listen to 2nd candidate
3. Toggle a "Repeat previous annotation" button
4. Watch the yes/no/unknown, tag(s), and comment automatically toggle/fill to match the previous values entered by this moderator
5. Hit Submit

B:
1. Listen to all 5 candidates on the current page
2. For the first listed candidate, fill in tags and a comment that apply to all of the candidates
3. Hit a select all button near the top of the list
4. Then "Apply annotations" to all the candidates on the page (e.g. default 5)

C: 
1. Select a start and end datetime
2. Specify a status (yes, no, unknown, or maybe a new one "archive"?)
3. Specify any tag(s) and/or comment
4. Bulk process all candidates within the datetime range

I'm sure the UX/design team could get more/better feedback from other moderators, and then devise other/better solutions! Also, I  think Akash may have "cleared" some older back-logs, but I'm not sure how he accomplished it...

**Comment by micowan** [comment]
Hey Scott. In the Project Kanban board, should we have a separate column for Moderator API/UI items? Otherwise they might be spread across multiple columns.
